apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: ""
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ""
    spec:
      containers:
        - name: ""
          image: "rogoyalacr.azurecr.io/"
          ports:
          - containerPort: 80