apiVersion: v1
kind: Service
metadata:
    name: "rogoyalaks-6db6"
    labels:
        app: "rogoyalaks-6db6"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "rogoyalaks-6db6"