on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: $
    
    - uses: azure/docker-login@v1
      with:
        login-server: rogoyalacr.azurecr.io
        username: ${{ secrets.acr_rogoyalacr_username }}
        password: ${{ secrets.acr_rogoyalacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t rogoyalacr.azurecr.io/:${{ github.sha }}
        docker push rogoyalacr.azurecr.io/:${{ github.sha }}
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 
        images: rogoyalacr.azurecr.io/:${{ github.sha }}